name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag (z.B. v0.2.0)'
        required: true
      notes:
        description: 'Release Notes (Markdown)'
        required: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate tag format
        run: |
          if [[ ! "${{ github.event.inputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag Format ungültig (erwartet vMAJOR.MINOR.PATCH)"; exit 1; fi
      - name: Create Tag
        run: |
          git config user.name "github-actions";
          git config user.email "actions@github.com";
          git tag ${{ github.event.inputs.tag }};
          git push origin ${{ github.event.inputs.tag }};
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: LernArena ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.notes || 'Automatischer Release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
